
name: Metrics

on:
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Medias1
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          user: ochiantropos
          filename: metrics_base.svg
          base: ""
          plugin_lines: yes 
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          token: ${{secrets.OCHI_CUSTOMIZE}}
          config_timezone: Europe/Kiev
      - name: Medias2
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          user: ochiantropos
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: activity
          plugin_topics_limit: 15
          filename: metrics_topics.svg
          token: ${{secrets.OCHI_CUSTOMIZE}}
          config_timezone: Europe/Kiev
      - name: Medias3
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          user: ochiantropos
          base: ""
          filename: anime_move.svg
          plugin_anilist_user: OchiAntropos
          plugin_anilist: yes
          token: ${{secrets.OCHI_CUSTOMIZE}}
          config_timezone: Europe/Kiev
          plugin_anilist_sections: characters
          plugin_anilist_shuffle: yes
          plugin_anilist_limit_characters: 22
      - name: Medias4
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          base: ""
          user: ochiantropos
          filename: anime_characters.svg
          plugin_anilist_user: OchiAntropos
          plugin_anilist: yes
          plugin_anilist_medias: anime
          token: ${{secrets.OCHI_CUSTOMIZE}}
          config_timezone: Europe/Kiev
          plugin_anilist_sections: favorites
          plugin_anilist_shuffle: yes
          plugin_anilist_limit: 6
      - name: Medias5
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          base: ""
          user: ochiantropos
          plugin_languages: yes
          plugin_languages_recent_days: 365
          plugin_languages_details: bytes-size,percentage,lines
          plugin_languages_sections: recently-used,most-used
          plugin_languages_colors: rainbow
          filename: metrics_lang.svg
          token: ${{secrets.OCHI_CUSTOMIZE}}
          config_timezone: Europe/Kiev
      - name: Medias6
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          base: ""
          user: ochiantropos
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_limit: 5
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_provider: spotify
          filename: metrics_songs.svg
          token: ${{secrets.OCHI_CUSTOMIZE}}
          config_timezone: Europe/Kiev
      - name: Compact display
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          user: ochiantropos
          token: ${{ secrets.OCHI_CUSTOMIZE }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
      - name: Repositories traffic
        uses: lowlighter/metrics@latest
        with:
          base: ""
          user: ochiantropos
          filename: traffic.svg
          token: ${{ secrets.OCHI_CUSTOMIZE }}
          base: repositories
          plugin_traffic: yes