name: Metrics

on:
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Medias1
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics_base.svg
          user: ochiantropos 
          base: header, repositories
          plugin_lines: yes 
      - name: Medias1
        uses: lowlighter/metrics@latest
        with:
          base: ""
          user: ochiantropos          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          filename: metrics_calendar.svg
          token: ${{secrets.OCHI_CUSTOMIZE}}
          config_timezone: Europe/Kiev
      - name: Medias2
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          user: ochiantropos
          plugin_topics: yes
          base: ""
          plugin_topics_mode: icons
          plugin_topics_sort: activity
          plugin_topics_limit: 15
          filename: metrics_topics.svg
          token: ${{secrets.OCHI_CUSTOMIZE}}
          config_timezone: Europe/Kiev
      - name: Medias3
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          user: ochiantropos
          filename: anime_move.svg
          base: ""
          plugin_anilist_user: OchiAntropos
          plugin_anilist: yes
          token: ${{secrets.OCHI_CUSTOMIZE}}
          config_timezone: Europe/Kiev
          plugin_anilist_sections: characters
          plugin_anilist_shuffle: yes
          plugin_anilist_limit_characters: 22
      - name: Medias4
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          user: ochiantropos
          filename: anime_characters.svg
          base: ""
          plugin_anilist_user: OchiAntropos
          plugin_anilist: yes
          plugin_anilist_medias: anime
          token: ${{secrets.OCHI_CUSTOMIZE}}
          config_timezone: Europe/Kiev
          plugin_anilist_sections: favorites
          plugin_anilist_shuffle: yes
          plugin_anilist_limit: 6

      - name: Medias5
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          user: ochiantropos
          plugin_languages: yes
          base: ""
          plugin_languages_sections: recently-used
          filename: metrics_lang.svg
          token: ${{secrets.OCHI_CUSTOMIZE}}
          config_timezone: Europe/Kiev
      - name: Medias6
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          user: ochiantropos
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_limit: 5
          base: ""
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_provider: spotify
          filename: metrics_songs.svg
          token: ${{secrets.OCHI_CUSTOMIZE}}
          config_timezone: Europe/Kiev