name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: ochiantropos
          plugin_anilist_user: OchiAntropos
          filename: metrics.svg
          token: ${{secrets.OCHI_CUSTOMIZE}}
          #template: classic
          #base: header, activity, community, repositories, metadata
          plugin_topics: yes
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_topics_limit: 10
          plugin_anilist: yes
          plugin_anilist_limit.characters: 22
          plugin_anilist_limit: 5
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_shuffle: yes
          config_timezone: Europe/Kiev
